### ISSUE TITLE
ImportError: cannot import name '_registerMatType' from 'cv2.cv2'

### ISSUE THREAD

**Issue by Drjacky** [n-gao/collage-generator#3]
```python
collage-generator git:(master) python3 collage_generator.py Images/6  --output example_collage.png --width 4096 --height 2048
Traceback (most recent call last):
  File "/collage-generator/collage_generator.py", line 6, in <module>
    import cv2
  File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 9, in <module>
    from .cv2 import _registerMatType
ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (/usr/local/lib/python3.9/site-packages/cv2/cv2.cpython-39-darwin.so)
```

I've installed the cv2 like this: `pip3 install opencv-python`

**Comment by n-gao** [comment]
Interesting, but this doesn't seem to be related to my code at all but to your OpenCV installation. could you create a new conda environment or try installing opencv via conda?
